"""The declarative base, and the two column types every table repeats.

Kept apart from the engine so that Alembic can import the metadata without opening a
connection — a migration tool that needs a running database to describe a schema is a
migration tool that cannot run in CI.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Annotated

from sqlalchemy import DateTime, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, mapped_column


class Base(DeclarativeBase):
    pass


def utcnow() -> datetime:
    """Timezone-aware, always.

    `datetime.utcnow()` returns a naive value that claims nothing about its zone, and
    comparing one to an aware value raises. docs/12 says storage is UTC everywhere; this
    is what makes that true rather than aspirational.
    """
    return datetime.now(UTC)


# Ids are generated by whoever creates the row — the device, usually (ADR-0015). The
# server default exists for rows the server itself creates, like a refresh token, and
# never overrides an id that arrived with a request.
UuidPk = Annotated[
    uuid.UUID,
    mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4),
]

# `timestamptz`, because a weather application that stores naive local times has a bug
# waiting for the next DST boundary (docs/12).
TimestampTz = Annotated[
    datetime,
    mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False),
]
