"""saved profiles and locations

Revision ID: 7076432cefad
Revises: a5caf7e44a3e
Create Date: 2026-09-03 03:52:21.654788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7076432cefad'
down_revision: Union[str, Sequence[str], None] = 'a5caf7e44a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_locations_user_id', 'saved_locations', ['user_id'], unique=False)
    op.create_index('uq_saved_locations_one_current', 'saved_locations', ['user_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('saved_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('activity', sa.String(length=32), nullable=False),
    sa.Column('temp_min', sa.Integer(), nullable=False),
    sa.Column('temp_max', sa.Integer(), nullable=False),
    sa.Column('wind_max_kmh', sa.Integer(), nullable=False),
    sa.Column('precip_max_pct', sa.Integer(), nullable=False),
    sa.Column('uv_max', sa.Integer(), nullable=True),
    sa.Column('preferred_hours', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('array_length(preferred_hours, 1) = 2', name='ck_saved_profiles_hours_pair'),
    sa.CheckConstraint('temp_min <= temp_max', name='ck_saved_profiles_temp_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_saved_profiles_user_id', 'saved_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_profiles_user_id', table_name='saved_profiles')
    op.drop_table('saved_profiles')
    op.drop_index('uq_saved_locations_one_current', table_name='saved_locations', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_saved_locations_user_id', table_name='saved_locations')
    op.drop_table('saved_locations')
    # ### end Alembic commands ###
